# version: "3"
# docker-compose.yml: `version` is obsolete"

services:

  # docker容器创建后，在Exec输入`psql -U postgres`进入容器内的PostgreSQL命令行。
  database:
    image: postgis/postgis:16-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    ports:
      - 5433:5432
    volumes:
      # 这里宿主机路径，正常安装pgsql的话是在PostgreSQL/{version}/data/下，这里可以映射到容器内的/var/lib/postgresql/data/
      - ./docker_volumes/database:/var/lib/postgresql/data
      # 这里的相对路径是相对于执行docker compose up命令的目录。
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg19990314"
      POSTGRES_DB: "directus"
    healthcheck:
      test: [ "CMD", "pg_isready", "--host=localhost", "--username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    image: redis:6
    ports:
      - 6380:6379
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: skydtrtzmr/my-directus:latest
    ports:
      - 8056:8055
    # 注意volume的路径，默认是在根目录的uploads和extensions下，而开发时是在api目录下。记得复制出来，不要污染源代码。
    volumes:
      - ./docker_volumes/uploads:/directus/uploads
      - ./docker_volumes/extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
      # environment:
      # SECRET: "replace-with-secure-random-value"

      # 注意这边信息要与上面database的POSTGRES_USER、POSTGRES_PASSWORD、POSTGRES_DB保持一致
      # DB_CLIENT: "pg"
      # DB_HOST: "database"
      # DB_PORT: "5432"
      # DB_DATABASE: "directus"
      # DB_USER: "directus"
      # DB_PASSWORD: "directus"
      # 上面这个端口是映射到容器内的，所以要用5432。
      # DB_USER: "postgres"
      # DB_PASSWORD: "pg19990314"

      # CACHE_ENABLED: "true"
      # CACHE_AUTO_PURGE: "true"
      # CACHE_STORE: "redis"
      # REDIS: "redis://cache:6379"

      # 注意设置CORS（跨域资源共享）
      # CORS_ENABLED: "true"
      # CORS_ORIGIN: "true"

      # ADMIN_EMAIL: "admin@example.com"
      # ADMIN_PASSWORD: "d1r3ctu5"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"

      # Environment variables can also be defined in a file (for example `.env`):
      #   # 直接用.env文件覆盖掉环境变量
    env_file:
      - .env
